# Generated by Django 3.1.2 on 2020-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('exclude_from_export', models.BooleanField(db_index=True, default=False, verbose_name='Исключить из экспорт')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Зарегестрирован в')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Telegram Id')),
            ],
        ),
    ]
