# Generated by Django 3.1.2 on 2020-10-23 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Названия розыгрыша')),
                ('start_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Страт розыгрыша')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='Окончания розыгрыша')),
            ],
            options={
                'verbose_name': 'Розыгрышь',
                'verbose_name_plural': 'Розыгрыши',
            },
        ),
    ]
