# Generated by Django 3.1.2 on 2020-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
                ('published', models.BooleanField(default=False, verbose_name='Публиковать')),
            ],
            options={
                'verbose_name': 'Ребус',
                'verbose_name_plural': 'Ребусы',
            },
        ),
    ]
