# Generated by Django 3.1.2 on 2020-10-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rebus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='telegram_bot.rebus', verbose_name='Ребус'),
        ),
        migrations.CreateModel(
            name='RebusAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_recieved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ответ получен в')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ Юзера')),
                ('rebus_sendet_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ребус отправлен в')),
                ('rebus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebus_attempts', to='telegram_bot.rebus', verbose_name='Ребус')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_attempts', to='telegram_bot.user', verbose_name='User')),
            ],
        ),
    ]
