# Generated by Django 3.1.2 on 2020-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_auto_20201023_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebusattempt',
            options={'verbose_name': 'Попытка решить ребус', 'verbose_name_plural': 'Попытки решить ребус'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='rebus',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
