# Generated by Django 3.1.2 on 2020-10-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_auto_20201023_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebus',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_attempts', to='telegram_bot.user', verbose_name='Участник'),
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.SlugField(verbose_name='Текущий вопрос')),
                ('poll_finished', models.BooleanField(default=False, verbose_name='Закончил опрос')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начал опрос в')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Закончил опрос в')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
