# Generated by Django 3.1.2 on 2020-10-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_auto_20201026_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestionAnswerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('asked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Получил вопрос в')),
                ('answered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ответил в')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.pollresult', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
