# Generated by Django 3.1.2 on 2020-10-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_pollquestionanswerpair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollquestionanswerpair',
            old_name='quiz',
            new_name='poll',
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_results', to='telegram_bot.user', verbose_name='Участник'),
        ),
    ]
