# Generated by Django 3.1.2 on 2020-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_auto_20201027_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rebus_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текущее состояния бота'),
        ),
    ]
