# Generated by Django 3.1.2 on 2020-10-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_user_rebus_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws', to='telegram_bot.draw', verbose_name='Розыгрышь'),
        ),
    ]
