# Generated by Django 3.1.2 on 2020-10-30 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_user_draw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'verbose_name': 'Розыгрыш', 'verbose_name_plural': 'Розыгрыши'},
        ),
        migrations.AddField(
            model_name='user',
            name='received_gift',
            field=models.BooleanField(default=False, verbose_name='Получил подарок'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime, verbose_name='Старт розыгрыша'),
        ),
    ]
