# Generated by Django 3.1.2 on 2020-11-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_auto_20201031_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebus',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
