# Generated by Django 3.1.2 on 2020-11-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_auto_20201112_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_competition',
            field=models.CharField(choices=[('РЕБУС', 'is_rebus'), ('ОПРОС', 'is_poll'), ('РЕГИСТРАЦИЯ', 'is_registration')], default='is_registration', max_length=20),
        ),
    ]
