# Generated by Django 3.1.2 on 2020-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0018_auto_20201112_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='current_question',
            field=models.IntegerField(default=0, verbose_name='Текущий вопрос'),
        ),
    ]
