# Generated by Django 3.1.2 on 2020-11-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0019_auto_20201112_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_rebus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
