# Generated by Django 3.1.2 on 2020-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0021_user_success_attemps_curent_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_competition',
            field=models.CharField(blank=True, choices=[('РЕБУС', 'is_rebus'), ('ОПРОС', 'is_poll')], max_length=20, null=True),
        ),
    ]
