# Generated by Django 3.1.2 on 2020-11-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_auto_20201115_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exclude_from_export',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Исключить из экспорта'),
        ),
    ]
