# Generated by Django 3.1.2 on 2020-11-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False  # Renaming the 'telegram_bot_user' table while in a transaction is not supported on SQLite < 3.26
    dependencies = [
        ('telegram_bot', '0023_auto_20201118_0224'),
    ]

    operations = [
        migrations.RenameModel('User', 'Player'),
        migrations.AlterField(
            model_name='pollresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_results', to='telegram_bot.player', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_attempts', to='telegram_bot.player', verbose_name='Участник'),
        ),
    ]
