# Generated by Django 3.1.2 on 2020-11-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0024_auto_20201120_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='received_gift',
            new_name='gift_received',
        ),
        migrations.RenameField(
            model_name='rebusattempt',
            old_name='answer_recieved_at',
            new_name='answer_received_at',
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Зарегистрирован в'),
        ),
    ]
