# Generated by Django 3.1.2 on 2020-11-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0025_auto_20201121_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rebus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='telegram_bot.rebus', verbose_name='Ребус'),
        ),
        migrations.AlterField(
            model_name='player',
            name='telegram_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram Id'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='rebus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebus_attempts', to='telegram_bot.rebus', verbose_name='Ребус'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='telegram_bot.player', verbose_name='Участник'),
        ),
    ]
