# Generated by Django 3.1.2 on 2020-11-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0028_remove_player_success_attempts_current_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rebus_state',
            new_name='bot_state',
        ),
    ]
