# Generated by Django 3.1.2 on 2020-11-23 13:23

from django.db import migrations


def del_null_value_in_rebus_attempt(apps, schema_editor):
    RebusAttempt = apps.get_model('telegram_bot', 'RebusAttempt')
    Rebus = apps.get_model('telegram_bot', 'Rebus')
    Player = apps.get_model('telegram_bot', 'Player')
    rebus = Rebus.objects.first()
    player = Player.objects.first()
    all_attempts = RebusAttempt.objects.all()
    if all_attempts:
        for attempt in all_attempts:
            if attempt.rebus is None or attempt.rebus == '':
                attempt.rebus = rebus

            if attempt.user is None or attempt.user == '':
                attempt.user == player
            
            attempt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0029_auto_20201122_0032'),
    ]

    operations = [
        migrations.RunPython(del_null_value_in_rebus_attempt),
    ]
