# Generated by Django 3.1.2 on 2020-11-23 13:37

from django.db import migrations


def del_null_value_in_player(apps, schema_editor):
    Player = apps.get_model('telegram_bot', 'Player')
    players = Player.objects.all()
    if players:
        for player in players:
            try:
                if player.success_attemps_curent_session or player.success_attemps_curent_session is None:
                    player.delete()
            except AttributeError:
                if player.full_name is None or player.full_name == '':
                    player.full_name = ''

                if player.phone_number is None or player.phone_number == '':
                    player.phone_number == ''

                player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0030_auto_20201123_1623'),
    ]

    operations = [
        migrations.RunPython(del_null_value_in_player),
    ]
