# Generated by Django 3.1.2 on 2020-11-23 14:50

from django.db import migrations


def set_player_fields(apps, schema_editor):
    Player = apps.get_model('telegram_bot', 'Player')
    players = Player.objects.all()
    if players:
        for player in players:
            if not player.bot_state:
                player.bot_state = ''
                player.save()
            if not player.current_competition:
                player.current_competition = ''
                player.save()
            if not player.full_name:
                player.full_name = ''
                player.save()
            if not player.phone_number:
                player.phone_number = ''
                player.save()
           

def set_rebus_field(apps, schema_editor):
    Rebus = apps.get_model('telegram_bot', 'Rebus')
    rebuses = Rebus.objects.all()
    if rebuses:
        for rebus in rebuses:
            if not rebus.text:
                rebus.text = ''
                rebus.save()
            if not rebus.hint:
                rebus.hint = ''
                rebus.save()


def set_rebus_attempt_fields(apps, schema_editor):
    Player = apps.get_model('telegram_bot', 'Player')
    RebusAttempt = apps.get_model('telegram_bot', 'RebusAttempt')
    Rebus = apps.get_model('telegram_bot', 'Rebus')
    attempts = RebusAttempt.objects.all()
    if attempts:
        for attempt in attempts:
            if not attempt.rebus:
                attempt.rebus = Rebus.objects.first()
                attempt.save()
            if not attempt.user:
                attempt.user = Player.objects.first()
                attempt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0031_auto_20201123_1637'),
    ]

    operations = [
        migrations.RunPython(set_player_fields),
        migrations.RunPython(set_rebus_field),
        migrations.RunPython(set_rebus_attempt_fields),
    ]
