# Generated by Django 3.1.2 on 2020-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0032_auto_20201123_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт машина для ребуса', max_length=100, verbose_name='Текущее состояния бота'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_competition',
            field=models.CharField(blank=True, choices=[('РЕБУС', 'is_rebus'), ('ОПРОС', 'is_poll')], max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='rebus',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='rebus',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='rebus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebus_attempts', to='telegram_bot.rebus', verbose_name='Ребус'),
        ),
        migrations.AlterField(
            model_name='rebusattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='telegram_bot.player', verbose_name='Участник'),
        ),
    ]
